Creation of the first JavaScript project Library
gonjavi/JavascriptLibrary pull request #1
Opened 2020-01-25 16:12 UTC by gonjavi

Things done in this pull request:

- Created the main Index file, adding the form for new books and create the table with titles to display the books at the bottom. 

- Added materialize for styling.

- Created the js folder in which I included the main script.js file and other files for materialize.

- Created the folder CSS in which some styling files for materialize were included.

- Completed the steps 1-6 from the oding project: https://www.theodinproject.com/courses/javascript/lessons/library

2020-01-26 02:55 UTC, gonjavi commented
What to do here? Do I need modules? or any different setup?  or I just need to continue trying to fix it.

2020-01-26 21:51 UTC, shloch requested changes
hello @gonjavi 
Works perfect, great job..

I like the design 😊😊

## [required changes]
- Linter errors...... try to make them all green
- make sure the number of pages, accept numbers 

Waiting for last re-review hopefully

Happy coding 😊

2020-01-27 18:15 UTC, shloch approved these changes
# Hello @gonjavi 

![accomplished](https://user-images.githubusercontent.com/40712459/73201483-644e0f00-4139-11ea-98dc-c535620afc66.jpg)

You can merge, happy coding

2020-01-27 18:15 UTC, shloch commented on js/script.js
> +  }
👏👏👏👏

2020-01-27 18:26 UTC, gonjavi commented on js/script.js
> +  }
thanks

2020-01-27 18:27 UTC, merged